import { Move } from '@/models/move';
import { MoveType } from '@/models/move-type';

const emptyCharacterStats = {
  id: 0,
  weight: 0,
  gravity: 0,
  walkSpeed: 0,
  runSpeed: 0,
  initialDash: 0,
  dashFrames: 0,
  waveDashLength: 0,
  waveDashLengthRank: 0,
  plaIntangibilityFrames: 0,
  jumpSquat: 0,
  canWallJump: false,
  notes: '',
};

export const ShowCaseMoves: Move[] = [
  {
    id: 1233,
    name: 'Down Air',
    normalizedName: 'dair',
    totalFrames: 49,
    type: MoveType.air,
    isInterpolated: false,
    start: 5,
    end: 27,
    pngUrl: 'https://i.fightcore.gg/png/fox/dair.png',
    gifUrl: 'https://i.fightcore.gg/beta/fox/dair.gif',
    webmUrl: 'https://i.fightcore.gg/beta/fox/dair.webm',
    characterId: 224,
    character: {
      moves: [],
      name: 'Fox',
      normalizedName: 'fox',
      fightCoreId: 224,
      characterStatistics: emptyCharacterStats,
    },
  },
  {
    id: 834,
    name: 'Forward Air',
    normalizedName: 'fair',
    totalFrames: 33,
    start: 4,
    end: 7,
    type: MoveType.air,
    isInterpolated: false,
    pngUrl: 'https://i.fightcore.gg/png/marth/fair.png',
    gifUrl: 'https://i.fightcore.gg/beta/marth/fair.gif',
    webmUrl: 'https://i.fightcore.gg/beta/marth/fair.webm',
    characterId: 222,
    character: {
      moves: [],
      name: 'Marth',
      normalizedName: 'marth',
      fightCoreId: 222,
      characterStatistics: emptyCharacterStats,
    },
  },
  {
    id: 1335,
    name: 'Down Air',
    normalizedName: 'dair',
    totalFrames: 49,
    start: 5,
    end: 24,
    type: MoveType.air,
    isInterpolated: false,
    pngUrl: 'https://i.fightcore.gg/png/falco/dair.png',
    gifUrl: 'https://i.fightcore.gg/beta/falco/dair.gif',
    webmUrl: 'https://i.fightcore.gg/beta/falco/dair.webm',
    characterId: 218,
    character: {
      moves: [],
      name: 'Falco',
      normalizedName: 'falco',
      fightCoreId: 218,
      characterStatistics: emptyCharacterStats,
    },
  },
  {
    id: 961,
    name: 'Back Air',
    normalizedName: 'bair',
    totalFrames: 39,
    start: 9,
    end: 12,
    type: MoveType.air,
    isInterpolated: false,
    pngUrl: 'https://i.fightcore.gg/png/jigglypuff/bair.png',
    gifUrl: 'https://i.fightcore.gg/beta/jigglypuff/bair.gif',
    webmUrl: 'https://i.fightcore.gg/beta/jigglypuff/bair.webm',
    characterId: 214,
    character: {
      moves: [],
      name: 'Jigglypuff',
      normalizedName: 'jigglypuff',
      fightCoreId: 214,
      characterStatistics: emptyCharacterStats,
    },
  },
  {
    id: 1227,
    name: 'Up Smash',
    normalizedName: 'usmash',
    totalFrames: 41,
    start: 7,
    end: 17,
    type: MoveType.unknown,
    isInterpolated: false,
    pngUrl: 'https://i.fightcore.gg/png/fox/usmash.png',
    gifUrl: 'https://i.fightcore.gg/beta/fox/usmash.gif',
    webmUrl: 'https://i.fightcore.gg/beta/fox/usmash.webm',
    characterId: 224,
    character: {
      moves: [],
      name: 'Fox',
      normalizedName: 'fox',
      fightCoreId: 224,
      characterStatistics: emptyCharacterStats,
    },
  },
  {
    id: 830,
    name: 'Forward Smash',
    normalizedName: 'fsmash',
    totalFrames: 33,
    start: 4,
    end: 7,
    type: MoveType.air,
    isInterpolated: false,
    pngUrl: 'https://i.fightcore.gg/png/marth/fsmash.png',
    gifUrl: 'https://i.fightcore.gg/beta/marth/fsmash.gif',
    webmUrl: 'https://i.fightcore.gg/beta/marth/fsmash.webm',
    characterId: 222,
    character: {
      moves: [],
      name: 'Marth',
      normalizedName: 'marth',
      fightCoreId: 222,
      characterStatistics: emptyCharacterStats,
    },
  },
  {
    id: 1103,
    name: 'Forward Air',
    normalizedName: 'fair',
    totalFrames: 39,
    start: 14,
    end: 30,
    type: MoveType.air,
    isInterpolated: false,
    pngUrl: 'https://i.fightcore.gg/png/captainfalcon/fair.png',
    gifUrl: 'https://i.fightcore.gg/beta/captainfalcon/fair.gif',
    webmUrl: 'https://i.fightcore.gg/beta/captainfalcon/fair.webm',
    characterId: 227,
    character: {
      moves: [],
      name: 'Captain Falcon',
      normalizedName: 'captainfalcon',
      fightCoreId: 227,
      characterStatistics: emptyCharacterStats,
    },
  },
  {
    id: 1131,
    name: 'Forward Air',
    normalizedName: 'fair',
    totalFrames: 33,
    start: 5,
    end: 7,
    type: MoveType.air,
    isInterpolated: false,
    pngUrl: 'https://i.fightcore.gg/png/sheik/fair.png',
    gifUrl: 'https://i.fightcore.gg/beta/sheik/fair.gif',
    webmUrl: 'https://i.fightcore.gg/beta/sheik/fair.webm',
    characterId: 260,
    character: {
      moves: [],
      name: 'Sheik',
      normalizedName: 'sheik',
      fightCoreId: 260,
      characterStatistics: emptyCharacterStats,
    },
  },
];
